services:
  redis:
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: always
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.3'

  api-gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - MESSAGE_SERVICE_URL=${MESSAGE_SERVICE_URL}
      - EXTERNAL_DATA_SERVICE_URL=${EXTERNAL_DATA_SERVICE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - auth-service
    restart: always
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.3'

  auth-service:
    build: ./auth_service
    ports:
      - "8001:8001"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.3' 